replicaCount: 1

image:
  repository: ghcr.io/bluicezhen/metapi
  tag: "41767a6"
  digest: ""
  pullPolicy: Always

service:
  type: NodePort
  port: 4000
  nodePort: 30400

persistence:
  hostPath: /home/ubuntu/metapi/data

existingSecret: "metapi-secrets"